### ISSUE TITLE
Generate secret key when deploying site

### ISSUE THREAD

**Issue by codersquid** [pyvideo/richard-ansible#7]
I do not know how to generate a password for SECRET_KEY. I found a snippet I am playing around with. It's not ready to be checked in. for now the SECRET_KEY is set by hand in the roles/richard/defaults/main.yml file.

```
---
- hosts: localhost
  tasks:
    - local_action: shell openssl passwd -1 -in /dev/urandom | head -1
      register: secret_key
    - local_action: debug msg="secret_key is ${secret_key.stdout}"
```
